joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 10

move_position_ctrlr:
  joint: move_1_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}

move_velocity_ctrlr:
  joint: move_1_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

move_effort_ctrlr:
  joint: move_1_joint
  type: effort_controllers/JointEffortController
  pid: {p: 1.0, i: 0.0, d: 0.0}

move_2_position_ctrlr:
  joint: move_2_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}

move_2_velocity_ctrlr:
  joint: move_2_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

move_2_effort_ctrlr:
  joint: move_2_joint
  type: effort_controllers/JointEffortController
  pid: {p: 1.0, i: 0.0, d: 0.0}

